### ISSUE TITLE
CSV file

### ISSUE THREAD

**Issue by promise7091** [malawski/cloudworkflowsimulator#139]
Hi.

i wanted to know where can i find some examples for creating multi data-centers and transfer jobs between them?
and would you tell me some description  about seed(what's seed for)?

thank you.

**Comment by bryk** [comment]
seed - seed for random number generator. If you want to develop/test the simulator you often use it to get reproducible results.

multi datacenters - currently it is not supported. Everything runs in a single data center on single core homogeneous VMs. You're free to modify the simulator for your needs, though :)
