### ISSUE TITLE
Bug in calculating predicted release time of a VM

### ISSUE THREAD

**Issue by aciepiela** [malawski/cloudworkflowsimulator#140]
I think there is a bug in this method: https://github.com/malawski/cloudworkflowsimulator/blob/master/src/cws/core/VM.java#L492

We calculate expected running time based on transfer time and computation time. When a job is running (in computation phase) then it has all of his input files transferred to the machine already so the `StorageManager` (which has cache) will always return 0 here, but if these files had to be transferred to the machine earlier then real `runningTime` will include this time.

As a result `remaining` time will be less than it actually is. We use it in `WorkflowAndLocalityAwareEnsembleScheduler` and fixing this may (slightly I guess)  improve this algorithm. 

Suggested solution:
If a job is in input transfer phase: `remaining = expectedTransferTime - inputTransferElapsedTime + expectedComputationTime`
If a job is in computation phase: `remaining = expectedComputationTime - elapsedComputationTime + expectedTransferTime`
If a job is in output transfer phase: `remaining = expectedTransferTime`

Calling @bryk here. Is my reasoning correct?

**Comment by aciepiela** [comment]
... and probably because of this bug we check if total is less than zero here: https://github.com/malawski/cloudworkflowsimulator/blob/master/src/cws/core/VM.java#L511

**Comment by bryk** [comment]
You're correct. Feel free to fix this.
