### ISSUE TITLE
Should we consider cache/RAM usage while assigning tasks to VMs?

### ISSUE THREAD

**Issue by aciepiela** [malawski/cloudworkflowsimulator#141]
Right now when we have homogenous, one-core VMs we don't care whether a tasks input/output files can fit in a VMs memory, because if they don't then the whole cloud doesn't make any sense.

But when we consider heterogenous clouds with multi-core VMs I think we should include this. We assume that every task will run on each core so input/output files for all tasks may not fit in memory at once. 

I've checked what's the maximum sum of all input/output files for a single task and here are the results:
CYBERSHAKE - 39GB
GENOME - 14GB
LIGO - 53MB
MONTAGE - 1GB

So for Cybershake and Genome they are significant. With an 8-core VM we may theoretically need 8 * 39 GB Ram to run all tasks. Otherwise some tasks may have to wait in a queue or use disk instead of RAM.

So, should we include RAM (and its current usage) while assigning tasks to VMs?
Calling @pkoniu , @malawski , @ziaber

**Comment by ziaber** [comment]
It all depends on how much slower disk is than RAM. If loading files from disk space significantly affects speed of execution then we should include RAM while assigning tasks, and moreover we should also include disk speed.

**Comment by aciepiela** [comment]
> It all depends on how much slower disk is than RAM.

A lot: http://www.eecs.berkeley.edu/~rcs/research/interactive_latency.html

> we should also include disk speed

What for? If we assume that tasks will have all of their data in memory then there is no need for disks. We have global storage for intermediate files so we transfer all files to memory from it and later from memory to this storage via network.

**Comment by pkoniu** [comment]
When it comes to counting price for different vm providers then we have to remember to count it for machine that has enough ram for given task, don't we?

**Comment by ziaber** [comment]
@aciepiela so you want to execute tasks on machine only if it has enough free RAM space, and don't consider disk space at all?

**Comment by aciepiela** [comment]
Yes. If there is enough free RAM to hold both input and output files then given task will be executed. Otherwise it will wait in a queue. 

Swapping between RAM and disk is slow. What's more, we don't have any data in DAGs to include such executions.

**Comment by ziaber** [comment]
If so I think that your assumption is correct and we should go this way,

**Comment by aciepiela** [comment]
So as per today meeting, we decided that we can store input/output files on a VM's hard drive and that we shouldn't consider RAM when assigning tasks to VMs. 

This may be a future extension though.
