### ISSUE TITLE
Decide how to choose the best VM for predicting runtimes, workflow admission, DAGStats etc.

### ISSUE THREAD

**Issue by aciepiela** [malawski/cloudworkflowsimulator#168]
DAGStats, workflow admissioners etc. need a VM to calculate predicted runtime, critical path etc. With homogenous environment this is trivial, because there is only one VM.

We need to decide what VM to provide to these objects with heterogenous environment: the fastest one, one with the best performance/price ratio, an artificial one (average price and performance) or maybe some other heuristic?

**Comment by aciepiela** [comment]
We decided that we should extract this functionality and hide it behind an interface and implement 3 different methods of choosing the best VM for prediction: the fastest VM (optimistic approach), most efficient (performance/price ratio) and a synthetic/average machine.

**Comment by pkoniu** [comment]
Closed with:
https://github.com/malawski/cloudworkflowsimulator/pull/172
https://github.com/malawski/cloudworkflowsimulator/pull/175
